CREATE TABLE stores (
    id SERIAL PRIMARY KEY,
    owner INTEGER REFERENCES users(id),
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    store_type VARCHAR,
    store_id VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)
